
IF OBJECT_ID('[dbo].[FINVIZ_REAL_TIME_PRICES]', 'U') IS NOT NULL
DROP TABLE [dbo].FINVIZ_REAL_TIME_PRICES
GO
CREATE TABLE FINVIZ_REAL_TIME_PRICES
(
Num INT,
Ticker NVARCHAR(20) NULL,
PerfWeek NVARCHAR(20) NULL,
PerfMonth NVARCHAR(20) NULL,
PerfQuarter NVARCHAR(20) NULL,
PerfHalf NVARCHAR(20) NULL,
PerfYear NVARCHAR(20) NULL,
PerfYTD NVARCHAR(20) NULL,
VolatilityWeek NVARCHAR(20) NULL,
VolatilityMonth NVARCHAR(20) NULL,
Recom NVARCHAR(20) NULL,
AvgVolume NVARCHAR(20) NULL,
RelVolume NVARCHAR(20) NULL,
Price FLOAT NULL,
Change NVARCHAR(20) NULL,
Volume BIGINT NULL
);
GO


IF OBJECT_ID('[dbo].[FINVIZ_TICKER_INDUSTRY]', 'U') IS NOT NULL
DROP TABLE [dbo].FINVIZ_TICKER_INDUSTRY
GO
CREATE TABLE FINVIZ_TICKER_INDUSTRY
(
Ticker NVARCHAR(20) NULL,
Company NVARCHAR(200) NULL,
Setor NVARCHAR(100) NULL,
Industry NVARCHAR(100) NULL,
Country NVARCHAR(100) NULL
);
GO


SELECT *
FROM FINVIZ_TICKER_INDUSTRY





DROP TABLE TICKER_BY_EXCHANGE_RAW_DATA

TRUNCATE TABLE TICKER_BY_EXCHANGE_RAW_DATA

IF OBJECT_ID('[dbo].[TICKER_BY_EXCHANGE]', 'U') IS NOT NULL
DROP TABLE [dbo].TICKER_BY_EXCHANGE
GO
CREATE TABLE TICKER_BY_EXCHANGE
(
Symbol NVARCHAR(10) NOT NULL,
Exchange NVARCHAR(10) NOT NULL
);
GO



SELECT Symbol,COUNT(*)
FROM TICKER_BY_EXCHANGE
GROUP BY Symbol
ORDER BY 2

INSERT INTO TICKER_BY_EXCHANGE(Symbol,Exchange)
SELECT Symbol, 'NYSE'
FROM TICKER_BY_EXCHANGE_RAW_DATA

