


SELECT 'US Stock Market' Market
	  ,SUM(B.[]]
; -50%]]]) ']
; -50%]'
	  ,SUM(B.[]]-50%; -30%]]]) ']-50%; -30%]'
	  ,SUM(B.[]]-30%; -15%]]]) ']-30%; -15%]'
	  ,SUM(B.[]]-15%;0]]]) ']-15%;0]'
	  ,SUM(B.[]]0%; 5%]]]) ']0%; 5%]'
	  ,SUM(B.[]]5%; 20%]]]) ']5%; 20%]'
	  ,SUM(B.[]]20%; 
[]) ']20%; 
['
	  ,SUM(B.[Liquidity_]]
; -50%]]]) 'Liquidity_]
; -50%]'
	  ,SUM(B.[Liquidity_]]-50%; -30%]]]) 'Liquidity_]-50%; -30%]'
	  ,SUM(B.[Liquidity_]]-30%; -15%]]]) 'Liquidity_]-30%; -15%]'
	  ,SUM(B.[Liquidity_]]-15%;0]]]) 'Liquidity_]-15%;0]'
	  ,SUM(B.[Liquidity_]]0%; 5%]]]) 'Liquidity_]0%; 5%]'
	  ,SUM(B.[Liquidity_]]5%; 20%]]]) 'Liquidity_]5%; 20%]'
	  ,SUM(B.[Liquidity_]]20%; 
[]) 'Liquidity_]20%; 
['
	  ,SUM(B.DailyLiquidity) DailyLiquidity
FROM 
(
SELECT A.TICKER
	  ,A.NAME_COMPANY
	  ,A.ID_DATE
	  ,A.EOY_PRICE
	  ,A.OPEN_PRICE
	  ,A.LOW_PRICE
	  ,A.HIGH_PRICE
	  ,A.CLOSE_PRICE
	  ,A.VOLUME
	  ,A.YTD    
        ,CASE WHEN YTD <= -0.5 THEN 1 ELSE 0 END AS ']
; -50%]'
        ,CASE WHEN YTD > -0.5 AND YTD <= -0.3 THEN 1 ELSE 0 END AS ']-50%; -30%]'
        ,CASE WHEN YTD > -0.3 AND YTD <= -0.15 THEN 1 ELSE 0 END AS ']-30%; -15%]'
        ,CASE WHEN YTD > -0.15 AND YTD <=0  THEN 1 ELSE 0 END AS ']-15%;0]'
        ,CASE WHEN YTD > 0 AND YTD <= 0.05 THEN 1 ELSE 0 END AS ']0%; 5%]'
        ,CASE WHEN YTD > 0.05 AND YTD <= 0.2 THEN 1 ELSE 0 END AS ']5%; 20%]'
        ,CASE WHEN YTD > 0.2 THEN 1 ELSE 0 END AS ']20%; 
['
        ,CASE WHEN YTD <= -0.5 THEN CLOSE_PRICE * VOLUME ELSE 0 END AS 'Liquidity_]
; -50%]'
        ,CASE WHEN YTD > -0.5 AND YTD <= -0.3 THEN CLOSE_PRICE * VOLUME ELSE 0 END AS 'Liquidity_]-50%; -30%]'
        ,CASE WHEN YTD > -0.3 AND YTD <= -0.15 THEN CLOSE_PRICE * VOLUME ELSE 0 END AS 'Liquidity_]-30%; -15%]'
        ,CASE WHEN YTD > -0.15 AND YTD <=0  THEN CLOSE_PRICE * VOLUME ELSE 0 END AS 'Liquidity_]-15%;0]'
        ,CASE WHEN YTD > 0 AND YTD <= 0.05 THEN CLOSE_PRICE * VOLUME ELSE 0 END AS 'Liquidity_]0%; 5%]'
        ,CASE WHEN YTD > 0.05 AND YTD <= 0.2 THEN CLOSE_PRICE * VOLUME ELSE 0 END AS 'Liquidity_]5%; 20%]'
        ,CASE WHEN YTD > 0.2 THEN CLOSE_PRICE * VOLUME ELSE 0 END AS 'Liquidity_]20%; 
['
        ,CLOSE_PRICE * VOLUME DailyLiquidity

FROM
(
SELECT A.TICKER,C.NAME_COMPANY,A.ID_DATE,CAST(B.OPEN_PRICE AS FLOAT) EOY_PRICE,CAST(A.OPEN_PRICE AS FLOAT) OPEN_PRICE,CAST(A.LOW_PRICE AS FLOAT) LOW_PRICE,CAST(A.HIGH_PRICE AS FLOAT) HIGH_PRICE,CAST(A.CLOSE_PRICE AS FLOAT) CLOSE_PRICE,CAST(A.VOLUME AS FLOAT) VOLUME,
CAST(A.CLOSE_PRICE/B.CLOSE_PRICE - 1 AS float) YTD
FROM MARKETS.TEMP_DAILY_BARS A WITH(NOLOCK)
LEFT JOIN MARKETS.TEMP_DAILY_BARS B WITH(NOLOCK)
    ON A.TICKER = B.TICKER
INNER JOIN VW_STOCKS_ACTIVE C
    ON A.TICKER COLLATE SQL_Latin1_General_CP1_CI_AS = C.TICKER COLLATE SQL_Latin1_General_CP1_CI_AS
WHERE A.ID_DATE = 20220610
    AND B.ID_DATE = 20211231
    AND A.LOW_PRICE > 1
) A
) B

/*
Stock selection and analysis
*/
SELECT A.TICKER
	  ,A.NAME_COMPANY
	  ,A.ID_DATE
	  ,A.EOY_PRICE
	  ,A.OPEN_PRICE
	  ,A.LOW_PRICE
	  ,A.HIGH_PRICE
	  ,A.CLOSE_PRICE
	  ,A.VOLUME
	  ,A.YTD    
FROM
(
SELECT A.TICKER,C.NAME_COMPANY,A.ID_DATE,CAST(B.OPEN_PRICE AS FLOAT) EOY_PRICE,CAST(A.OPEN_PRICE AS FLOAT) OPEN_PRICE,CAST(A.LOW_PRICE AS FLOAT) LOW_PRICE,CAST(A.HIGH_PRICE AS FLOAT) HIGH_PRICE,CAST(A.CLOSE_PRICE AS FLOAT) CLOSE_PRICE,CAST(A.VOLUME AS FLOAT) VOLUME,
CAST(A.CLOSE_PRICE/B.CLOSE_PRICE - 1 AS float) YTD
FROM MARKETS.TEMP_DAILY_BARS A WITH(NOLOCK)
LEFT JOIN MARKETS.TEMP_DAILY_BARS B WITH(NOLOCK)
    ON A.TICKER = B.TICKER
INNER JOIN VW_STOCKS_ACTIVE C
    ON A.TICKER COLLATE SQL_Latin1_General_CP1_CI_AS = C.TICKER COLLATE SQL_Latin1_General_CP1_CI_AS
WHERE A.ID_DATE = 20220610
    AND B.ID_DATE = 20211231
    AND A.LOW_PRICE > 1
) A
ORDER BY A.YTD DESC